### ISSUE TITLE
Feature: User can add a medication

### ISSUE THREAD

**Issue by kepsteen** [kepsteen/MediTrak#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add details about a medication they are currently taking to the database

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can input details about a medication into a form so that the medication will be added to the database

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Landing Page](https://github.com/user-attachments/assets/809adb74-7cb5-41d8-9771-2e5d5a05ed5d)
![Add Medication](https://github.com/user-attachments/assets/67822ba9-5142-4ecf-a89e-486cf050dbe3)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Set up the endpoint for a post request to add a medication in server.ts
- [x] Test the endpoint with httpie
- [x] Create the mobile Landing Page
  - [x] Create a header component
  - [x] Add the markup for the landing page
- [x] Make the landing page responsive
- [x] Create an Add Medication component
- [x] Create the Routes for the landing page and the add medication page
- [x] Add the markup for the add Medication Page to render the add medication form
- [x] Add the state variables for the form fields to make the form controlled
- [x] Add the handleSubmit event handler
  - [x] prevent the default behavior of the submit event
  - [x] create a fetch request to submit the form inputs to the medications table
  - [x] reset the state values
