### ISSUE TITLE
Feature: User can log medications taken

### ISSUE THREAD

**Issue by kepsteen** [kepsteen/MediTrak#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click log when they have a taken a medication for that day

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the daily schedule view the user can click to log a medication that they have taken today

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![View Medications__Schedule (2)](https://github.com/user-attachments/assets/cf161519-5e11-420b-9faa-05444b8fdb31)
![View Medications__Schedule (3)](https://github.com/user-attachments/assets/8ae2d6ad-e69f-4056-8979-54770104b182)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create an express route to handle decrementing / incrementing the dose count
- [ ] Create a new component MedStatusDot that can be clicked to log the status of a medication
  - [ ] Should take the medicationId as a prop
- [ ] Create a state variable to keep track of the clicked / not clicked state of the dot
- [ ] Add a handleClick function that does the following: 
  - [ ] Checks the state of the dot to determine if the pill count should be decremented or incremented
  - [ ] create a fetch request to the /api/medications/:medicationId/inventory endpoint to apply the operation to the remaining pill count in the database
  - [ ] Toggles the state of the isClicked state
