### ISSUE TITLE
Feature: User can create an account and log in to view their medications

### ISSUE THREAD

**Issue by kepsteen** [kepsteen/MediTrak#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click sign up for an account and log in to view their medications and schedules

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

From the landing page the user will be prompted to sign up or sign in which take them to an authentication page where they can sign up for an account or log in

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Registration](https://github.com/user-attachments/assets/18e8b18f-6683-40c5-bcb6-429cfdb44f4f)
![Authorization](https://github.com/user-attachments/assets/fb5d1ea0-647a-4fe7-a88d-d7cdcc9e4653)
![Registration (1)](https://github.com/user-attachments/assets/e4cc0e31-e699-4d9f-baed-391f4fedcbd7)
![Authorization (1)](https://github.com/user-attachments/assets/cd9ef09e-79fe-48ae-92c9-d20dca028db5)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Install argon2 and jsonwebtoken packages
- [x] Implement sign up endpoint (place before other endpoints)
  - [x] Check to make sure both username and password were provided
  - [x] hash the password with argon2
  - [x] insert username, hashedpassword, and role
- [x] Add the sign in endpoint
  - [x] check to make sure both username and password provided
  - [x] query for the user in the database
  - [x] check if user exists
  - [x] if user exists verify the password with the verify method
  - [x] if user verified create payload with the userId and the username and sign the payload into a json web token
- [x] add the authorization middleware to all the other routes
- [x] Create the markup for the sign in and sign up components
- [x] Create an Authpage component that will be the parent to the sign in and sign up components
  - [x] The AuthPage will take one prop mode, which will be either signup or sign in. 
  - [x] Based on the mode either the signup or sign in components will be rendered
- [x] Create a User Provider component that will wrap the routes and provide the user, token, handle signin, handle signout 
- [x] Create a custom hook useUser to that can be called to use the context values
