### ISSUE TITLE
Feature: User can add a caregiver to their account

### ISSUE THREAD

**Issue by kepsteen** [kepsteen/MediTrak#16]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click sign up for an account and log in to view their medications and schedules

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can click on link in the navbar to go their profile page. In the profile page they go to the caregivers tab to add a caregiver

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Profile__Account](https://github.com/user-attachments/assets/695ddf02-054c-4a33-bf46-19f27954cea2)
![Profile__Caregivers](https://github.com/user-attachments/assets/4f80eefc-3460-4f40-8942-7ab6ed20358c)
![Select Patient](https://github.com/user-attachments/assets/8e963f7a-e2d8-4702-8cc9-ab7f3fdbf627)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add select role to Register form to select the role
- [x] if Patient is selected add date of birth input
- [x] In profile, if the account is a caregiver the caregivers tab should display patient and the other way around
- [x] In Medications layout, if the user is a caregiver there should be a select option for the patients
- [x] Once a patient is selected the caregiver must input the patients date of birth to access their schedule and medication list
- [x] Refactor the get medications endpoint to send the userId in the body of the request
- [x] Refactor the get schedules endpoint to send the userId in the body of the request

- [x] Refactor the fetch Medications and getch Schedules to send the current selected user in the body of the request if the user is a caregiver
