### ISSUE TITLE
Feature: User can opt in for low pill count text reminders

### ISSUE THREAD

**Issue by kepsteen** [kepsteen/MediTrak#20]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User's can opt in for text message reminders when creating an account

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will recieve text messages reminding them to refill their precriptions when their meds are running low

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Install twilio
- [x] set up environment variables for twilio Account SID, Twilio Auth Token
- [x] create a twilio client
- [x] Refactor the medications inventory express endpoint to check if the remaining amount is less than 10
  - [x] If so, query the database for the user's phone number
  - [x] create a message with the medication name, the prescriber and the count
  - [x] send the message 
  - [x] Add secrets to aws for deployed site
