### ISSUE TITLE
Feature: User can view their medications

### ISSUE THREAD

**Issue by kepsteen** [kepsteen/MediTrak#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their medications and details

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can navigate to the medications page where they will see a list of the medications they have added to their profile

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![View Medications__List](https://github.com/user-attachments/assets/25bf5f94-40b4-4c3a-b13c-3159c7c42c94)

![View Medications__List (1)](https://github.com/user-attachments/assets/56203e45-86ac-4424-8752-cdef77226db4)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Set up endpoint for retrieving medications from the database
- [x] Create a file for the MedicationsList Component
  - [x] create the jsx markup for the component 
  - [x] create a medicaitons state variable to hold the list of medications
  - [x] On component mount and every time the user's medications change fetch the list of meds for the user from the database
