### ISSUE TITLE
Feature: User can create a medication schedule

### ISSUE THREAD

**Issue by kepsteen** [kepsteen/MediTrak#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a medication schedule

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can navigate to the medications schedule page and will be prompted to create a schedule

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Add Medication Schedule](https://github.com/user-attachments/assets/5402040e-0faa-426a-ab57-fd8d424a393e)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a post route to the backend to create a medicationSchedule
- [x] Create a MedicationSchedule component
- [x] Create a Medications Layout component
  - [x] Import the Tab component from Shadcn
  - [x] Create a tab for the MedicationList and the MedicationSchedule
  - [x] move the medications state variable and the useEffect that fetches the medications from the MedicationList up to the parent MedicationsLayout component
    - [x] Pass down the medications state variable from MedicationsLayout to the children as props 
  - [x] Create a AddMedicationScheduleForm component
    - [x] Create the jsx markup for the form
      - [x] The form should Include two fields days (days of the week) and frequency per day and a submit button
      - [x] The form will display the currently selected medication name
    - [x] Create a state variable to track the index of the medication in the medications array
    - [x] Handle the submission of the form
      - [x] create a submit handler function that does the folllowing:
        - [x] sends a fetch request to the server to add a medication schedule for each medication
        - [x] increments the selected index
        - [x] resets the values of the form 
- [x] Change the /medications route to render  the MedicationsLayout component
