### ISSUE TITLE
Feature: User can view their daily medication schedule

### ISSUE THREAD

**Issue by kepsteen** [kepsteen/MediTrak#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their medication schedule

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can navigate to the medications schedule and view their daily med schedule

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![View Medications__Schedule (2)](https://github.com/user-attachments/assets/cf161519-5e11-420b-9faa-05444b8fdb31)
![View Medications__Schedule (3)](https://github.com/user-attachments/assets/8ae2d6ad-e69f-4056-8979-54770104b182)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create an express route for getting the medication schedules
- [x] Create the markup for the daily schedule list
  - [x] Display today's date
  - [x] Render each medication in it's corresponding time of day
- [x] Fetch the medication schedules and display the current days schedule
